definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  standard__front_page:
    weight: -50
    menu_name: main
    parent: ''
    expanded: false
    enabled: true
  user__page:
    menu_name: account
    parent: ''
    weight: -10
    expanded: true
    enabled: true
  user__logout:
    weight: -50
    parent: user.page
    menu_name: account
    enabled: true
    expanded: false
_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
